version: '2'
services:
    insiap_proposal-app:
        image: insiap_proposal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://insiap_proposal-mysql:3306/insiap_proposal?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    insiap_proposal-mysql:
        extends:
            file: mysql.yml
            service: insiap_proposal-mysql
